# Generated by Django 2.1.5 on 2020-04-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PintPrice',
            fields=[
                ('googleId', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('barName', models.CharField(max_length=128)),
                ('price', models.IntegerField()),
                ('price_unit', models.CharField(default='£', max_length=12)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
