# Generated by Django 2.1.5 on 2020-06-08 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('googleId', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('barName', models.CharField(max_length=128)),
                ('image_reference', models.CharField(blank=True, max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('BeerName', models.CharField(max_length=128, unique=True)),
                ('BeerBrand', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PintPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('price_unit', models.IntegerField(choices=[(1, '£'), (2, '$'), (3, '€')], default='£')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheap_pints.Bar')),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheap_pints.Beer')),
            ],
        ),
        migrations.AddField(
            model_name='bar',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cheap_pints.City'),
        ),
        migrations.AlterUniqueTogether(
            name='pintprice',
            unique_together={('beer', 'bar')},
        ),
    ]
