# Generated by Django 2.1.5 on 2020-04-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheap_pints', '0002_auto_20200412_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='pintprice',
            name='photo_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
