# Generated by Django 2.1.5 on 2020-04-19 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheap_pints', '0002_auto_20200419_1526'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pintprice',
            unique_together={('beer', 'bar')},
        ),
    ]
