# Generated by Django 2.1.5 on 2020-04-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheap_pints', '0002_auto_20200418_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pintprice',
            name='price_unit',
            field=models.CharField(choices=[(1, '£'), (2, '$'), (3, '€')], default='£', max_length=1),
        ),
    ]
