# Generated by Django 2.1.5 on 2020-04-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheap_pints', '0003_pintprice_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pintprice',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='pintprice',
            name='image_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
