# Generated by Django 2.1.5 on 2020-04-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheap_pints', '0003_auto_20200418_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='price_unit',
            field=models.CharField(choices=[(1, '£'), (2, '$'), (3, '€')], default='£', max_length=12),
        ),
    ]
