# Generated by Django 2.1.5 on 2020-04-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheap_pints', '0005_auto_20200414_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('bar_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('googleId', models.CharField(max_length=128)),
                ('barName', models.CharField(max_length=128)),
                ('price', models.FloatField()),
                ('price_unit', models.CharField(default='£', max_length=12)),
                ('image_reference', models.CharField(blank=True, max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PintPrie',
            fields=[
                ('bar_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('googleId', models.CharField(max_length=128)),
                ('barName', models.CharField(max_length=128)),
                ('price', models.FloatField()),
                ('price_unit', models.CharField(default='£', max_length=12)),
                ('image_reference', models.CharField(blank=True, max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PintPrice',
        ),
    ]
