# Generated by Django 2.1.5 on 2020-04-17 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheap_pints', '0006_auto_20200417_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bars',
            fields=[
                ('bar_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('googleId', models.CharField(max_length=128)),
                ('barName', models.CharField(max_length=128)),
                ('price', models.FloatField()),
                ('price_unit', models.CharField(default='£', max_length=12)),
                ('image_reference', models.CharField(blank=True, max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Beers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('BeerName', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PintPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('price_unit', models.CharField(default='£', max_length=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('BeerTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PintPriceBeerId', to='cheap_pints.Beers')),
                ('googleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PrintPriceGoogleId', to='cheap_pints.Bars')),
            ],
        ),
        migrations.DeleteModel(
            name='Bar',
        ),
        migrations.DeleteModel(
            name='PintPrie',
        ),
    ]
